services:
  front-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    restart: always
    networks:
      - front-network

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - API/.env
    networks:
      - back-network
    command: npm run start:dev

volumes:
  mongodb_data:

networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge
